cfg={       
        'diffusion':{
            'T':500            
        },
        'training':{
            'batch_size':128,
            'num_epochs':15,
            'lr':0.001,
            'save_path':'./logs/',
            'data_path':'/home/dhruvb/adrl/datasets/img_align_celeba_resampled/',
            'file_extn':'jpg',
            'chkpt_path':'./chkpt/celeba/',
            'chkpt_file':'expt_1a_celeba.chk.pt',
            'load_from_chkpt':False
        },
        'ddpm':{
            'image_size':64,
            'channels':3
        }
    }