cfg={        
        'diffusion':{
            'T':500            
        },
        'training':{
            'batch_size':64,
            'num_epochs':500,
            'lr':0.0001,
            'save_path':'./logs/',
            'data_path':'/home/dhruvb/adrl/datasets/bitmojis_resampled/',
            'file_extn':'png',
            'chkpt_path':'./chkpt/',
            #'chkpt_file':'expt_1a_bitmojis.chk.pt',
            'chkpt_file':'expt_2_bitmojis.chk.pt',
            'load_from_chkpt':False
        },
        'ddpm':{
            'image_size':64,
            'channels':3
        },
        'ebm':{
            'step_size': 10,
            'num_steps':60,
            'alpha':.001,
            'buffer_len':100,
            'buffer_shape':(3,64,64)
        }
    }